/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppFarmRouteImport } from './routes/_app.farm'
import { Route as AppAgentRouteImport } from './routes/_app.agent'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppFieldsIdRouteImport } from './routes/_app.fields.$id'
import { Route as AppAgentFieldsRouteImport } from './routes/_app.agent.fields'
import { Route as AppAgentDashboardRouteImport } from './routes/_app.agent.dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminFieldsRouteImport } from './routes/_app.admin.fields'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmRoute = AppFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldsIdRoute = AppFieldsIdRouteImport.update({
  id: '/fields/$id',
  path: '/fields/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentFieldsRoute = AppAgentFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAgentDashboardRoute = AppAgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFieldsRoute = AppAdminFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agent': typeof AppAgentRouteWithChildren
  '/farm': typeof AppFarmRoute
  '/profile': typeof AppProfileRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/fields': typeof AppAdminFieldsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/fields': typeof AppAgentFieldsRoute
  '/fields/$id': typeof AppFieldsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agent': typeof AppAgentRouteWithChildren
  '/farm': typeof AppFarmRoute
  '/profile': typeof AppProfileRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/fields': typeof AppAdminFieldsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/fields': typeof AppAgentFieldsRoute
  '/fields/$id': typeof AppFieldsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/agent': typeof AppAgentRouteWithChildren
  '/_app/farm': typeof AppFarmRoute
  '/_app/profile': typeof AppProfileRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/fields': typeof AppAdminFieldsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/agent/dashboard': typeof AppAgentDashboardRoute
  '/_app/agent/fields': typeof AppAgentFieldsRoute
  '/_app/fields/$id': typeof AppFieldsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin'
    | '/agent'
    | '/farm'
    | '/profile'
    | '/auth/complete-profile'
    | '/admin/dashboard'
    | '/admin/fields'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/fields'
    | '/fields/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin'
    | '/agent'
    | '/farm'
    | '/profile'
    | '/auth/complete-profile'
    | '/admin/dashboard'
    | '/admin/fields'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/fields'
    | '/fields/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/admin'
    | '/_app/agent'
    | '/_app/farm'
    | '/_app/profile'
    | '/auth/complete-profile'
    | '/_app/admin/dashboard'
    | '/_app/admin/fields'
    | '/_app/admin/users'
    | '/_app/agent/dashboard'
    | '/_app/agent/fields'
    | '/_app/fields/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farm': {
      id: '/_app/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AppFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fields/$id': {
      id: '/_app/fields/$id'
      path: '/fields/$id'
      fullPath: '/fields/$id'
      preLoaderRoute: typeof AppFieldsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/fields': {
      id: '/_app/agent/fields'
      path: '/fields'
      fullPath: '/agent/fields'
      preLoaderRoute: typeof AppAgentFieldsRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/_app/agent/dashboard': {
      id: '/_app/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AppAgentDashboardRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/fields': {
      id: '/_app/admin/fields'
      path: '/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AppAdminFieldsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminFieldsRoute: typeof AppAdminFieldsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminFieldsRoute: AppAdminFieldsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAgentRouteChildren {
  AppAgentDashboardRoute: typeof AppAgentDashboardRoute
  AppAgentFieldsRoute: typeof AppAgentFieldsRoute
}

const AppAgentRouteChildren: AppAgentRouteChildren = {
  AppAgentDashboardRoute: AppAgentDashboardRoute,
  AppAgentFieldsRoute: AppAgentFieldsRoute,
}

const AppAgentRouteWithChildren = AppAgentRoute._addFileChildren(
  AppAgentRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentRoute: typeof AppAgentRouteWithChildren
  AppFarmRoute: typeof AppFarmRoute
  AppProfileRoute: typeof AppProfileRoute
  AppFieldsIdRoute: typeof AppFieldsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentRoute: AppAgentRouteWithChildren,
  AppFarmRoute: AppFarmRoute,
  AppProfileRoute: AppProfileRoute,
  AppFieldsIdRoute: AppFieldsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
