/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as AppRouteImport } from './routes/_app.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAgentRouteImport } from './routes/_app.agent.tsx'
import { Route as AppAdminRouteImport } from './routes/_app.admin.tsx'
import { Route as AppFieldsIdRouteImport } from './routes/_app.fields.$id.tsx'
import { Route as AppAgentFieldsRouteImport } from './routes/_app.agent.fields.tsx'
import { Route as AppAgentDashboardRouteImport } from './routes/_app.agent.dashboard.tsx'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users.tsx'
import { Route as AppAdminFieldRouteImport } from './routes/_app.admin.field.tsx'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard.tsx'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldsIdRoute = AppFieldsIdRouteImport.update({
  id: '/fields/$id',
  path: '/fields/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentFieldsRoute = AppAgentFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAgentDashboardRoute = AppAgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAgentRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFieldRoute = AppAdminFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agent': typeof AppAgentRouteWithChildren
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/field': typeof AppAdminFieldRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/fields': typeof AppAgentFieldsRoute
  '/fields/$id': typeof AppFieldsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/agent': typeof AppAgentRouteWithChildren
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/field': typeof AppAdminFieldRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/fields': typeof AppAgentFieldsRoute
  '/fields/$id': typeof AppFieldsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/agent': typeof AppAgentRouteWithChildren
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/field': typeof AppAdminFieldRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/agent/dashboard': typeof AppAgentDashboardRoute
  '/_app/agent/fields': typeof AppAgentFieldsRoute
  '/_app/fields/$id': typeof AppFieldsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/agent'
    | '/admin/dashboard'
    | '/admin/field'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/fields'
    | '/fields/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/agent'
    | '/admin/dashboard'
    | '/admin/field'
    | '/admin/users'
    | '/agent/dashboard'
    | '/agent/fields'
    | '/fields/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/agent'
    | '/_app/admin/dashboard'
    | '/_app/admin/field'
    | '/_app/admin/users'
    | '/_app/agent/dashboard'
    | '/_app/agent/fields'
    | '/_app/fields/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fields/$id': {
      id: '/_app/fields/$id'
      path: '/fields/$id'
      fullPath: '/fields/$id'
      preLoaderRoute: typeof AppFieldsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/fields': {
      id: '/_app/agent/fields'
      path: '/fields'
      fullPath: '/agent/fields'
      preLoaderRoute: typeof AppAgentFieldsRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/_app/agent/dashboard': {
      id: '/_app/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AppAgentDashboardRouteImport
      parentRoute: typeof AppAgentRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/field': {
      id: '/_app/admin/field'
      path: '/field'
      fullPath: '/admin/field'
      preLoaderRoute: typeof AppAdminFieldRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminFieldRoute: typeof AppAdminFieldRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminFieldRoute: AppAdminFieldRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAgentRouteChildren {
  AppAgentDashboardRoute: typeof AppAgentDashboardRoute
  AppAgentFieldsRoute: typeof AppAgentFieldsRoute
}

const AppAgentRouteChildren: AppAgentRouteChildren = {
  AppAgentDashboardRoute: AppAgentDashboardRoute,
  AppAgentFieldsRoute: AppAgentFieldsRoute,
}

const AppAgentRouteWithChildren = AppAgentRoute._addFileChildren(
  AppAgentRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAgentRoute: typeof AppAgentRouteWithChildren
  AppFieldsIdRoute: typeof AppFieldsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAgentRoute: AppAgentRouteWithChildren,
  AppFieldsIdRoute: AppFieldsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
